name: CI Develop
on:
  push:
    branches:
      - 'feature**'
jobs:
  Merge-desde-develop:
    permissions: write-all
    name: Merge desde develop
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'CI-DEVELOP') }}
    steps:
      - name: Guardar nombre de la rama
        id: guardar-rama
        env:
          RAMA: ${GITHUB_REF#refs/heads/}
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
      - name: Mezcla develop -> ${{ steps.guardar-rama.outputs.branch }}
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: master
          target-branch: ${{ steps.guardar-rama.outputs.branch }}
  Pruebas-unitarias:
    name: Pruebas unitarias
    needs: Merge-desde-develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v3
      - name: Configuración de entorno de python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Instalación de librerías y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Correr pruebas unitarias
        id: correr-pruebas
        run: python -m unittest -v tests/test_persona.py
      - name: Cálculo de cubrimiento
        id: cubrimiento
        run: |
          coverage run -m unittest tests/test_persona.py
          coverage report -m
  Merge-a-develop:
    permissions: write-all
    name: Merge a develop
    needs: Pruebas-unitarias
    runs-on: ubuntu-latest
    steps:
      - name: Guardar nombre de la rama
        id: guardar-rama
        env:
          RAMA: ${GITHUB_REF#refs/heads/}
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
      - name: Mezcla ${{ steps.guardar-rama.outputs.branch }} -> develop
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: ${{ steps.guardar-rama.outputs.branch }}
          target-branch: master