name: CI Develop
on:
  push:
    branches:
      - 'feature**'
jobs:
  Pruebas:
    permissions: write-all
    name: Pruebas
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'CI-DEVELOP') }}
    steps:
      - name: Guardar rama
        id: guardar-rama
        env:
          RAMA: ${GITHUB_REF#refs/heads/}
        run: echo "rama=${RAMA}" >> $GITHUB_OUTPUT
      - name: Obtener rama
        id: obtener-rama
        run: echo ${{steps.guardar-rama.outputs.rama}}
      - name: Mezcla ${{ steps.guardar-rama.outputs.rama }} -> develop
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: ${{ steps.guardar-rama.outputs.rama }}
          target-branch: develop
      - name: Checkout de repositorio
        uses: actions/checkout@v2
      - name: Configuración de entorno de python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Instalación de librerías y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Correr pruebas
        id: correr-pruebas
        run: python -m unittest -v tests/test_persona.py
      - name: Cálculo de cubrimiento
        id: cubrimiento
        run: |
          coverage run -m unittest tests/test_persona.py
          coverage report -m